<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleCodeList [
<!ELEMENT SimpleCodeList (row)+>
<!ATTLIST SimpleCodeList 
	xmlns CDATA #FIXED "">
<!ELEMENT row (code,eng,fra)>
<!ATTLIST row 
	xmlns CDATA #FIXED "">
<!ELEMENT code (#PCDATA)>
<!ATTLIST code 
	xmlns CDATA #FIXED "">
<!ELEMENT eng (#PCDATA)>
<!ATTLIST eng 
	xmlns CDATA #FIXED "">
<!ELEMENT fra (#PCDATA)>
<!ATTLIST fra 
	xmlns CDATA #FIXED "">
]>
<SimpleCodeList>
	<row>
		<code>RegEnrolProcess</code>
		<eng>Regulatory Enrolment Process</eng>
		<fra>fr_Regulatory Enrolment Process</fra>
	</row>
	<row>
		<code>DossierInfo</code>
		<eng>Dossier Information</eng>
		<fra>fr_Dossier Information</fra>
	</row>
	<row>
		<code>HUMAN</code>
		<eng>Human</eng>
		<fra>fr_Human</fra>
	</row>
	<row>
		<code>RADIO</code>
		<eng>Radiopharmaceutical</eng>
		<fra>fr_Radiopharmaceutical</fra>
	</row>
	<row>
		<code>DISINFECT</code>
		<eng>Disinfectant</eng>
		<fra>fr_Disinfectant</fra>
	</row>
	<row>
		<code>VET</code>
		<eng>Veterinary</eng>
		<fra>fr_Veterinary</fra>
	</row>
	<row>
		<code>VETERINARY</code>
		<eng>Veterinary</eng>
		<fra>fr_Veterinary</fra>
	</row>
	<row>
		<code>EnrolStatus</code>
		<eng>Enrolment Status</eng>
		<fra>fr_Enrolment Status</fra>
	</row>
	<row>
		<code>EnrolVersion</code>
		<eng>Enrolment Version</eng>
		<fra>fr_Enrolment Version</fra>
	</row>
	<row>
		<code>DateLastSaved</code>
		<eng>Date Last Saved</eng>
		<fra>fr_Date Last Saved</fra>
	</row>
	<row>
		<code>DossierID</code>
		<eng>Dossier ID</eng>
		<fra>fr_Dossier ID</fra>
	</row>
	<row>
		<code>A_DossierType</code>
		<eng>Dossier Type</eng>
		<fra>fr_Dossier Type</fra>
	</row>
	<row>
		<code>B_CompanyID</code>
		<eng>Company ID</eng>
		<fra>fr_Company ID</fra>
	</row>
	<row>
		<code>C_SubmissionSignThird</code>
		<eng>C. The submission will be signed or filed by a third party on
				behalf of the manufacturer or sponsor</eng>
		<fra>fr_C. The submission will be signed or filed by a third party on
				behalf of the manufacturer or sponsor</fra>
	</row>
	<row>
		<code>Yes</code>
		<eng>Yes</eng>
		<fra>fr_Yes</fra>
	</row>
	<row>
		<code>No</code>
		<eng>No</eng>
		<fra>fr_No</fra>
	</row>
	<row>
		<code>D_ProductName</code>
		<eng>Product Name</eng>
		<fra>fr_Product Name</fra>
	</row>
	<row>
		<code>E_ProperCommonNonProrietaryName</code>
		<eng>Proper, Common or Non-Proprietary Name</eng>
		<fra>fr_Proper, Common or Non-Proprietary Name</fra>
	</row>
	<row>
		<code>DrugUse</code>
		<eng>Drug Use</eng>
		<fra>fr_Drug Use</fra>
	</row>
	<row>
		<code>G_RelatedInfo</code>
		<eng>Related Information</eng>
		<fra>fr_Related Information</fra>
	</row>
	<row>
		<code>H_Therapeutic</code>
		<eng>Therapeutic Classifications</eng>
		<fra>fr_Therapeutic Classifications</fra>
	</row>
	<row>
		<code>I_IsCaRefProduct</code>
		<eng>Is there a Canadian Reference Product or Canadian Reference Biologic Drug for Biosimilars?</eng>
		<fra>fr_Is there a Canadian Reference Product or Canadian Reference Biologic Drug for Biosimilars?</fra>
	</row>
	<row>
		<code>CaRefProduct</code>
		<eng>Canadian Reference Product</eng>
		<fra>fr_Canadian Reference Product</fra>
	</row>
	<row>
		<code>I_BrandName</code>
		<eng>Brand Name</eng>
		<fra>fr_Brand Name</fra>
	</row>
	<row>
		<code>I_CompanyName</code>
		<eng>Company Name (Full legal Name - no abbreviations)</eng>
		<fra>fr_Company Name (Full legal Name - no abbreviations)</fra>
	</row>
	<row>
		<code>B02-20160301-001</code>
		<eng>ANDS (Abbreviated New Drug Submission)</eng>
		<fra>ANDS (Présentation abrégée de drogue nouvelle)</fra>
	</row>
	<row>
		<code>B02-20160301-031</code>
		<eng>EU NDS (Extraordinary Use New Drug Submission)</eng>
		<fra>EU NDS (Présentation de drogue nouvelle pour usage exceptionnel)</fra>
	</row>
	<row>
		<code>B02-20160301-032</code>
		<eng>EUSNDS (Extraordinary Use Supplement to a New Drug Submission)</eng>
		<fra>EUSNDS (Supplément à une présentation de drogue nouvelle pour usage exceptionnel)</fra>
	</row>
	<row>
		<code>B02-20160301-038</code>
		<eng>Level 3 – Notice of Change</eng>
		<fra>fr_Level 3 – Notice of Change</fra>
	</row>
	<row>
		<code>B02-20160301-046</code>
		<eng>MPNC (Pre-NC Meeting)</eng>
		<fra>MPNC (Réunion préalable - PM)</fra>
	</row>
	<row>
		<code>B02-20160301-047</code>
		<eng>MPNDS (Pre-NDS Meeting)</eng>
		<fra>MPNDS (Réunion préalable – PDN)</fra>
	</row>
	<row>
		<code>B02-20160301-049</code>
		<eng>MPSNDS (Pre-SNDS Meeting)</eng>
		<fra>MPSNDS (Réunion préalable – RPPDN)</fra>
	</row>
	<row>
		<code>B02-20160301-050</code>
		<eng>NC (Notifiable Change)</eng>
		<fra>NC (Préavis de modification)</fra>
	</row>
	<row>
		<code>B02-20160301-051</code>
		<eng>NDS (New Drug Submission)</eng>
		<fra>NDS (Présentation de drogue nouvelle)</fra>
	</row>
	<row>
		<code>B02-20160301-067</code>
		<eng>PAND (Pandemic Application)</eng>
		<fra>PAND (Demande pandémique)</fra>
	</row>
	<row>
		<code>B02-20160301-068</code>
		<eng>PBRER-C(Periodic Benefit Risk Evaluation Report - Confirmatory)</eng>
		<fra>PBRER-C</fra>
	</row>
	<row>
		<code>B02-20160301-069</code>
		<eng>PBRER-PV (Periodic Benefit Risk Evaluation Report - Post-market Vigilance)</eng>
		<fra>PBRER-PV</fra>
	</row>
	<row>
		<code>B02-20160301-075</code>
		<eng>PRNDS (Priority Request NDS)</eng>
		<fra>FR_PRNDS (Priority Request NDS)</fra>
	</row>
	<row>
		<code>B02-20160301-077</code>
		<eng>PRSNDS (Priority Request SNDS)</eng>
		<fra>PRNDS (Demande de statut d'’évaluation prioritaire - PDN)</fra>
	</row>
	<row>
		<code>B02-20160301-078</code>
		<eng>PSUR-C (Periodic Safety Update Report - Conditional)</eng>
		<fra>PSUR-C (Rapport périodique de pharmacovigilance - Confirmation)</fra>
	</row>
	<row>
		<code>B02-20160301-079</code>
		<eng>PSUR-PV (Periodic Safety Update Report - Pharmacovigilance)</eng>
		<fra>PSUR-PV (Rapport périodique de pharmacovigilance - pharmacovigilance)</fra>
	</row>
	<row>
		<code>B02-20160301-080</code>
		<eng>RMP-PV (Risk Management Plan - Pharmacovigilance)</eng>
		<fra>RMP-PV (Plan de gestion des risques - Pharmacovigilance)</fra>
	</row>
	<row>
		<code>B02-20160301-082</code>
		<eng>SANDS (Supplement to an Abbreviated New Drug Submission)</eng>
		<fra>SANDS (Supplément à une présentation abrégée de drogue nouvelle)</fra>
	</row>
	<row>
		<code>B02-20160301-084</code>
		<eng>SNDS (Supplement to a New Drug Submission)</eng>
		<fra>SNDS (Supplément à une présentation de drogue nouvelle)</fra>
	</row>
	<row>
		<code>B02-20160301-085</code>
		<eng>SNDS-C (Supplement to a New Drug Submission - Conditional)</eng>
		<fra>SNDS-C (Supplément à 'une présentation de drogue nouvelle - Confirmation)</fra>
	</row>
	<row>
		<code>B02-20160301-087</code>
		<eng>UD-PV (Undefined Data Pharmacovigilance)</eng>
		<fra>UD-PV (Données non définies – Pharmacovigilance)</fra>
	</row>
	<row>
		<code>B02-20160301-088</code>
		<eng>UDRA (Undefined Regulatory Activity)</eng>
		<fra>UDRA (Activité réglementaire non définie)</fra>
	</row>
	<row>
		<code>B02-20160301-089</code>
		<eng>YBPR (Yearly Biologic Product Report)</eng>
		<fra>YBPR (Rapport annuel sur un produit biologique)</fra>
	</row>
	<row>
		<code>B02-20160301-028</code>
		<eng>DSUR (Development Safety Update Report)</eng>
		<fra>FR_DSUR (Development Safety Update Report)</fra>
	</row>
	<row>
		<code>B02-20160301-018</code>
		<eng>DINA (Application for Drug Identification Number)</eng>
		<fra>fr_DINA (Application for Drug Identification Number)</fra>
	</row>
	<row>
		<code>B02-20160301-019</code>
		<eng>DINB (Application for Drug Identification Number - Biologic)</eng>
		<fra>fr_DINB (Application for Drug Identification Number - Biologic)</fra>
	</row>
	<row>
		<code>B02-20160301-020</code>
		<eng>DIND (Application for Drug Identification Number - Disinfectant Product)</eng>
		<fra>fr_DIND (Application for Drug Identification Number - Disinfectant Product)</fra>
	</row>
	<row>
		<code>B02-20160301-021</code>
		<eng>DINF (Application for Drug Identification Number - Category IV Product)</eng>
		<fra>fr_DINF (Application for Drug Identification Number - Category IV Product)</fra>
	</row>
	<row>
		<code>B02-20160301-043</code>
		<eng>MPDIN (Pre-Submission Meeting Information)</eng>
		<fra>fr_MPDIN (Pre-Submission Meeting Information)</fra>
	</row>
	<row>
		<code>B02-20160301-070</code>
		<eng>PDC</eng>
		<fra>PDC (Post-Authorization Division 1 Change)</fra>
	</row>
	<row>
		<code>B02-20160301-071</code>
		<eng>PDC (Post-Authorization Division 1 Change)</eng>
		<fra>fr_PDC-B (Post-Authorization Division 1 Change - Biologics)</fra>
	</row>
<row><code>AB</code><eng>Alberta</eng><fra>Alberta</fra></row>
<row><code>BC</code><eng>British Columbia</eng><fra>Colombie-Britannique</fra></row>
<row><code>MB</code><eng>Manitoba</eng><fra>Île-du-Prince-Édouard</fra></row>
<row><code>NB</code><eng>New Brunswick</eng><fra>Manitoba</fra></row>
<row><code>NL</code><eng>Newfoundland and Labrador</eng><fra>Nouveau-Brunswick</fra></row>
<row><code>NT</code><eng>Northwest Territories</eng><fra>Nouvelle-Écosse</fra></row>
<row><code>NS</code><eng>Nova Scotia</eng><fra>Nunavut</fra></row>
<row><code>NU</code><eng>Nunavut</eng><fra>Ontario</fra></row>
<row><code>ON</code><eng>Ontario</eng><fra>Québec</fra></row>
<row><code>PE</code><eng>Prince Edward Island</eng><fra>Saskatchewan</fra></row>
<row><code>QC</code><eng>Quebec</eng><fra>Terre-Neuve et Labrador</fra></row>
<row><code>SK</code><eng>Saskatchewan</eng><fra>Territoires du Nord-Ouest</fra></row>
<row><code>YT</code><eng>Yukon</eng><fra>Yukon</fra></row>
<row><code>AL</code><eng>Alabama</eng><fra>Alabama</fra></row>
<row><code>AK</code><eng>Alaska</eng><fra>Alaska</fra></row>
<row><code>AZ</code><eng>Arizona</eng><fra>Arizona</fra></row>
<row><code>AR</code><eng>Arkansas</eng><fra>Arkansas</fra></row>
<row><code>CA</code><eng>California</eng><fra>Californie</fra></row>
<row><code>CO</code><eng>Colorado</eng><fra>Caroline du nord</fra></row>
<row><code>CT</code><eng>Connecticut</eng><fra>Caroline du sud</fra></row>
<row><code>DE</code><eng>Delaware</eng><fra>Colorado</fra></row>
<row><code>DC</code><eng>District of Columbia</eng><fra>Connecticut</fra></row>
<row><code>FL</code><eng>Florida</eng><fra>Dakota du nord</fra></row>
<row><code>GA</code><eng>Georgia</eng><fra>Dakota du sud</fra></row>
<row><code>HI</code><eng>Hawaii</eng><fra>Delaware</fra></row>
<row><code>ID</code><eng>Idaho</eng><fra>District de Columbia</fra></row>
<row><code>IL</code><eng>Illinois</eng><fra>Floride</fra></row>
<row><code>IN</code><eng>Indiana</eng><fra>Géorgie</fra></row>
<row><code>IA</code><eng>Iowa</eng><fra>Hawaii</fra></row>
<row><code>KS</code><eng>Kansas</eng><fra>Idaho</fra></row>
<row><code>KY</code><eng>Kentucky</eng><fra>Illinois</fra></row>
<row><code>LA</code><eng>Louisiana</eng><fra>Indiana</fra></row>
<row><code>ME</code><eng>Maine</eng><fra>Iowa</fra></row>
<row><code>MD</code><eng>Maryland</eng><fra>Kansas</fra></row>
<row><code>MA</code><eng>Massachusetts</eng><fra>Kentucky</fra></row>
<row><code>MI</code><eng>Michigan</eng><fra>L'état de New York</fra></row>
<row><code>MN</code><eng>Minnesota</eng><fra>L'état de washington</fra></row>
<row><code>MS</code><eng>Mississippi</eng><fra>Louisiane</fra></row>
<row><code>MO</code><eng>Missouri</eng><fra>Maine</fra></row>
<row><code>MT</code><eng>Montana</eng><fra>Maryland</fra></row>
<row><code>NE</code><eng>Nebraska</eng><fra>Massachusetts</fra></row>
<row><code>NV</code><eng>Nevada</eng><fra>Michigan</fra></row>
<row><code>NH</code><eng>New Hampshire</eng><fra>Minnesota</fra></row>
<row><code>NJ</code><eng>New Jersey</eng><fra>Mississippi</fra></row>
<row><code>NM</code><eng>New Mexico</eng><fra>Missouri</fra></row>
<row><code>NY</code><eng>New York</eng><fra>Montana</fra></row>
<row><code>NC</code><eng>North Carolina</eng><fra>Nebraska</fra></row>
<row><code>ND</code><eng>North Dakota</eng><fra>Nevada</fra></row>
<row><code>OH</code><eng>Ohio</eng><fra>New Hampshire</fra></row>
<row><code>OK</code><eng>Oklahoma</eng><fra>New Jersey</fra></row>
<row><code>OR</code><eng>Oregon</eng><fra>Nouveau-mexique</fra></row>
<row><code>PA</code><eng>Pennsylvania</eng><fra>Ohio</fra></row>
<row><code>RI</code><eng>Rhode Island</eng><fra>Oklahoma</fra></row>
<row><code>SC</code><eng>South Carolina</eng><fra>Oregon</fra></row>
<row><code>SD</code><eng>South Dakota</eng><fra>Pennsylvanie</fra></row>
<row><code>TN</code><eng>Tennessee</eng><fra>Rhode Island</fra></row>
<row><code>TX</code><eng>Texas</eng><fra>Tennessee</fra></row>
<row><code>UT</code><eng>Utah</eng><fra>Texas</fra></row>
<row><code>VT</code><eng>Vermont</eng><fra>Utah</fra></row>
<row><code>VA</code><eng>Virginia</eng><fra>Vermont</fra></row>
<row><code>WA</code><eng>Washington</eng><fra>Virginie</fra></row>
<row><code>WV</code><eng>West Virginia</eng><fra>Virginie-occidentale</fra></row>
<row><code>WI</code><eng>Wisconsin</eng><fra>Wisconsin</fra></row>
<row><code>WY</code><eng>Wyoming</eng><fra>Wyoming</fra></row>
<row><code>FIRSTNAME</code><eng>First Name</eng><fra>Prénom</fra></row>
<row><code>LASTNAME</code><eng>Last Name</eng><fra>Nom</fra></row>
<row><code>INITIALS</code><eng>Initials</eng><fra>Initiales</fra></row>
<row><code>LANGCORRESPOND</code><eng>Language of Correspondance</eng><fra>Langue de correspondance</fra></row>
<row><code>JOBTITLE</code><eng>Job Title</eng><fra>Titre de poste</fra></row>
<row><code>SALUTATION</code><eng>Salutation</eng><fra>Titre de civilité</fra></row>
<row><code>SALUT_MR</code><eng>Mr.</eng><fra>M.</fra></row>
<row><code>SALUT_MS</code><eng>Ms.</eng><fra>Mme</fra></row>
<row><code>SALUT_DR</code><eng>Dr.</eng><fra>Dr.</fra></row>
<row><code>SALUT_MRS</code><eng>Mrs.</eng><fra>Mlle</fra></row>
<row><code>ROLE_PRIMARY</code><eng>Primary</eng><fra>Primaire</fra></row>
<row><code>ROLE_SECONDARY</code><eng>Alternate</eng><fra>Alterner</fra></row>
<row><code>CONTACTEMAIL</code><eng>Email</eng><fra>Adresse électronique</fra></row>
<row><code>FAX_NUMBER</code><eng>Fax Number</eng><fra>Numéro de télécopieur</fra></row>
<row><code>PHONE_EXT</code><eng>Phone Extension</eng><fra>Poste</fra></row>
<row><code>ROLES</code><eng>Roles</eng><fra>fr_Roles</fra></row>
<row><code>PHONENUMBER</code><eng>Phone Number</eng><fra>Numéro de téléphone</fra></row>
<row><code>CONTACT_INFO</code><eng>Company Representative Information</eng><fra>fr_Company Representative Information</fra></row>
<row><code>AMEND</code><eng>Amend</eng><fra>fr_Amend</fra></row>
<row><code>REP_CONTACT</code><eng>REP Contact</eng><fra>fr_REP Contact</fra></row>
<row><code>ONE_ROLE</code><eng>Role</eng><fra>fr_Role</fra></row>
<row><code>ONE_ROLE_MED</code><eng>Medicinal Ingredient</eng><fra>fr_Medicinal Ingredient</fra></row>
<row><code>ONE_ROLE_NON_MED</code><eng>Non-medicinal Ingredient</eng><fra>fr_Non-medicinal Ingredient</fra></row>
<row><code>CONTACT_DETAILS</code><eng>Company Representative Details</eng><fra>fr_Company Representative Details</fra></row>
<row><code>ADD_CONTACT</code><eng>Add REP Contact</eng><fra>fr_Add REP Contact</fra></row>
<row><code>CONTACT_ROLE_LEGEND</code><eng>Select one or more roles for this company representative</eng><fra>fr_Select one or more roles for this company representative</fra></row>
<row><code>REPRES</code><eng>Representative</eng><fra>fr_Representative</fra></row>
<row><code>DELETE_REPRES</code><eng>Delete Company Rep.</eng><fra>fr_Delete Company Rep.</fra></row>
<row><code>SAVE_REPRES</code><eng>Save Company Rep.</eng><fra>fr_Save Company Rep.</fra></row>
<row><code>REQUIRED_DOC</code><eng>Required Documentation</eng><fra>fr_Required Documentation</fra></row>
<row><code>STATEMENT_REVENUE</code><eng>A statement signed by the individual responsible for the applicant's financial affairs is included to certify that the fee payable is greater than 10% of the anticipated gross revenue</eng><fra>fr_A statement signed by the individual responsible for the applicant's financial affairs is included to certify that the fee payable is greater than 10% of the anticipated gross revenue</fra></row>
<row><code>EST_MARKET_SHARE</code><eng>Estimated market share (that is [i.e.], product's market potential compared to the total market for similar products in Canada)</eng><fra>fr_Estimated market share (that is [i.e.], product's market potential compared to the total market for similar products in Canada)</fra></row>
<row><code>SIMILAR_PRODUCT</code><eng>Comparison to similar products on the Canadian market or other similar markets (e.g., United States, European Union)</eng><fra>fr_Comparison to similar products on the Canadian market or other similar markets (e.g., United States, European Union)</fra></row>
<row><code>SALES_HISTORY</code><eng>Sales history prior to product upgrades or sales history of similar products</eng><fra>fr_Sales history prior to product upgrades or sales history of similar products</fra></row>
<row><code>DEFER_STATEMENT</code><eng>The statement supporting the deferral request is included.</eng><fra>fr_The statement supporting the deferral request is included.</fra></row>
<row><code>MARKETING_PLAN</code><eng>Marketing plan/product plan for the drug product</eng><fra>fr_Marketing plan/product plan for the drug product</fra></row>
<row><code>AVG_SALES</code><eng>Average sale price and demand</eng><fra>fr_Average sale price and demand</fra></row>
<row><code>OTHER</code><eng>Other</eng><fra>Autre</fra></row>
<row><code>OTHER_DOC_DETAILS</code><eng>Other Documentation Details</eng><fra>fr_Other Documentation Details</fra></row>
<row><code>FEE_AMOUNT</code><eng>Fees</eng><fra>fr_Fees</fra></row>
<row><code>PAYMENT</code><eng>Payment</eng><fra>fr_Payment</fra></row>
<row><code>PAYMENT_METHODS</code><eng>Please select all the payment methods you intend to use</eng><fra>fr_Please select all the payment methods you intend to use</fra></row>
<row><code>PREFEERED_OPTION</code><eng>Bill Payment Service Option (preferred method)</eng><fra>fr_Bill Payment Service Option (preferred method)</fra></row>
<row><code>EXISTING_CREDIT</code><eng>Existing credit</eng><fra>fr_Existing credit</fra></row>
<row><code>BANK_WIRE</code><eng>Wire (include bank confirmation)</eng><fra>Wire (include bank confirmation)</fra></row>
<row><code>CREDIT</code><eng>Mastercard / Visa / Amex / Visa Debit / JCB International</eng><fra>fr_Mastercard / Visa / Amex / Visa Debit / JCB International</fra></row>
<row><code>CHEQUE</code><eng>Cheque</eng><fra>fr_Cheque</fra></row>
<row><code>MONEY_ORDER</code><eng>Money Order</eng><fra>fr_Money Order</fra></row>
<row><code>BANK_DRAFT</code><eng>International Bank Draft</eng><fra>fr_International Bank Draft</fra></row>
<row><code>COMPANY_ID</code><eng>Company ID</eng><fra>fr_Company ID</fra></row>
<row><code>DOSSIER_TYPE</code><eng>Dossier Type</eng><fra>fr_Dossier Type</fra></row>
<row><code>PRODUCT_NAME</code><eng>Product Name</eng><fra>fr_Product Name</fra></row>
<row><code>BIOLOGIC</code><eng>Biologic</eng><fra>fr_Biologic</fra></row>
<row><code>PHARMA</code><eng>Pharmaceutical</eng><fra>fr_Pharmaceutical</fra></row>
<row><code>PHARMACEUTICAL</code><eng>Pharmaceutical</eng><fra>fr_Pharmaceutical</fra></row>
<row><code>CONTROL_NUM</code><eng>Control Number</eng><fra>fr_Control Number</fra></row>
<row><code>DATE_SUBMITTED</code><eng>Date Submitted</eng><fra>fr_Date Submitted</fra></row>
<row><code>SEQUENCE_NUM</code><eng>Sequence Number</eng><fra>fr_Sequence Number</fra></row>
<row><code>REG_ACTIVITY</code><eng>Regulatory Activity</eng><fra>fr_Regulatory Activity</fra></row>
<row><code>SEQUENCE_DESCRIPT</code><eng>Sequence Description</eng><fra>fr_Sequence Description</fra></row>
<row><code>IS_SOLICITED</code><eng>Is this solicited information?</eng><fra>fr_Is this solicited information?</fra></row>
<row><code>SOLICITED_RQ</code><eng>Requester of Solicited Information</eng><fra>fr_Requester of Solicited Information</fra></row>
<row><code>PROJ_MANAGER_NAME</code><eng>Name of Regulatory Project Manager, if known</eng><fra>fr_Name of Regulatory Project Manager, if known</fra></row>
<row><code>IS_FEE_TRANSACTION</code><eng>Are new or revised fees associated with this transaction?</eng><fra>fr_Are new or revised fees associated with this transaction?</fra></row>
<row><code>SUB_CLASS</code><eng>Submission Class</eng><fra>fr_Submission Class</fra></row>
<row><code>FEE_DESCRIPTION</code><eng>Submission Description</eng><fra>fr_Submission Description</fra></row>
<row><code>DEFER_FEES</code><eng>A deferral of payment is requested with this transaction</eng><fra>fr_A deferral of payment is requested with this transaction</fra></row>
<row><code>FEE_REMISSION</code><eng>Fee Remission is requested with this transaction</eng><fra>fr_Fee Remission is requested with this transaction</fra></row>
<row><code>GROSS_REVENUE</code><eng>Anticipated gross revenue for this drug product during the fee verification period</eng><fra>fr_Anticipated gross revenue for this drug product during the fee verification period</fra></row>
<row><code>TEN_PERCENT_REVENUE</code><eng>10% of anticipated gross revenue</eng><fra>fr_10% of anticipated gross revenue</fra></row>
<row><code>REG_CONTACT_THIS</code><eng>Regulatory Activity Contact for THIS transaction</eng><fra>fr_Regulatory Activity Contact for THIS transaction</fra></row>
<row><code>REG_ACT_CONTACT</code><eng>Regulatory Activity Contact for THIS transaction</eng><fra>fr_Regulatory Activity Contact for THIS transaction</fra></row>
<row><code>COMPANY_NOABBREV</code><eng>Company Name (Full legal Name - no abbreviations)</eng><fra>fr_Company Name (Full legal Name - no abbreviations)</fra></row>
<row><code>ADDRESS_INFO</code><eng>B. Address Information</eng><fra>fr_B. Address Information</fra></row>
<row><code>COMPANY_INFO</code><eng>A. Company Information</eng><fra>fr_A. Company Information</fra></row>
<row><code>COMPANY_REP_THIS</code><eng>C. Company Representative</eng><fra>fr_C. Company Representative</fra></row>
<row><code>CONFIRM_REGULATORY</code><eng>I confirm that the above regulatory activity contact information is  valid.</eng><fra>fr_I confirm that the above regulatory activity contact information is  valid.</fra></row>
<row><code>STREET_SUITE</code><eng>Street / Suite</eng><fra>fr_Street / Suite</fra></row>
<row><code>CITY_TOWN</code><eng>City / Town</eng><fra>fr_City / Town</fra></row>
<row><code>PROVINCE</code><eng>Province</eng><fra>fr_Province</fra></row>
<row><code>COUNTRY</code><eng>Country</eng><fra>fr_Country</fra></row>
<row><code>POSTAL_ZIP</code><eng>Postal / ZIP Code</eng><fra>fr_Postal / ZIP Code</fra></row>
<row><code>en</code><eng>English</eng><fra>fr_English</fra></row>
<row><code>fr</code><eng>French</eng><fra>fr_French</fra></row>
<row><code>LIFECYCLE_TITLE</code><eng>Transaction Details</eng><fra>fr_Transaction Details</fra></row>
<row><code>COMPANY_TEMPLATE</code><eng>Company Template: Regulatory Enrolment Process (REP)</eng><fra>FR_Company Template: Regulatory Enrolment Process (REP)</fra></row>
<row><code>REG_COMPANY_ENROL</code><eng>Regulatory Company Enrolment</eng><fra>fr_Regulatory Company Enrolment</fra></row>
<row><code>APPL_STATUS</code><eng>Enrolment Status</eng><fra>fr_Enrolment Status</fra></row>
<row><code>ENROL_VERSION</code><eng>Enrolment Version</eng><fra>fr_Enrolment Version</fra></row>
<row><code>DATE_SAVED</code><eng>Date Last Saved</eng><fra>fr_Date Last Saved</fra></row>
<row><code>ADDR_INFO</code><eng>Address Information</eng><fra>fr_Address Information</fra></row>
<row><code>ADDR_RECO</code><eng>Address Records</eng><fra>fr_Address Records</fra></row>
<row><code>COMPANY</code><eng>Company</eng><fra>FR_Company</fra></row>
<row><code>IMP_COMP_ID</code><eng>Importer Company ID</eng><fra>fr_Importer Company ID</fra></row>
<row><code>ADDR_ROLE_LEGEND</code><eng>Select one or more roles for this company</eng><fra>fr_Select one or more roles for this company</fra></row>
<row><code>MANUFACT_SEL</code><eng>Manufacturer / Sponsor Mailing Address</eng><fra>fr_Manufacturer / Sponsor Mailing Address</fra></row>
<row><code>MAIL_SEL</code><eng>Regulatory Mailing / Annual Contact Address</eng><fra>fr_Regulatory Mailing / Annual Contact Address</fra></row>
<row><code>BILLING_SEL</code><eng>Billing Address</eng><fra>fr_Billing Address</fra></row>
<row><code>IMPORTER_SEL</code><eng>Canadian Importer Mailing Address</eng><fra>fr_Canadian Importer Mailing Address</fra></row>
<row><code>CONTACT_MANUFACTURER</code><eng>Manufacturer / Sponsor Contact</eng><fra>fr_Manufacturer / Sponsor Contact</fra></row>
<row><code>CONTACT_MAILING</code><eng>Regulatory Mailing / Annual Contact</eng><fra>fr_Regulatory Mailing / Annual Contact</fra></row>
<row><code>CONTACT_BILLING</code><eng>Billing Contact</eng><fra>fr_Billing Contact</fra></row>
<row><code>REPPRIMARY</code><eng>Primary REP contact</eng><fra>fr_Primary REP contact</fra></row>
<row><code>REPSECONDARY</code><eng>Alternate REP contact</eng><fra>fr_Alternate REP contact</fra></row>
<row><code>CONTACT_BY</code><eng>Contact By</eng><fra>fr_Contact By</fra></row>
<row><code>PHONE</code><eng>Phone</eng><fra>fr_Phone</fra></row>
<row><code>FAX</code><eng>Fax</eng><fra>fr_Fax</fra></row>
<row><code>EMAIL</code><eng>Email</eng><fra>fr_Email</fra></row>
<row><code>EXTENSION</code><eng>ext</eng><fra>fr_ext</fra></row>
<row><code>DRUG_PRODUCT</code><eng>Product Information</eng><fra>fr_Product Information</fra></row>
<row><code>DRUG_USE</code><eng>Drug Use</eng><fra>fr_Drug Use</fra></row>
<row><code>SCHEDULE_PRESC_STATUS</code><eng>Schedule and Prescription status (check all that apply): The product is</eng><fra>fr_Schedule and Prescription status (check all that applies): The product is</fra></row>
<row><code>SCHEDULE_C</code><eng>included in Schedule C (radiopharmacurticals) to the Food and Drugs Act</eng><fra>fr_included in Schedule C (radiopharmacurticals) to the Food and Drugs Act</fra></row>
<row><code>SCHEDULE_D</code><eng>included in Schedule D (biologicals) to the Food and Drugs Act</eng><fra>fr_included in Schedule D (biologicals) to the Food and Drugs Act</fra></row>
<row><code>SCHEDULE_F</code><eng>included in Schedule F (prescription drugs) to the Food and Drug Regulations</eng><fra>fr_included in Schedule F (prescription drugs) to the Food and Drug Regulations</fra></row>
<row><code>PROP_INDICATION</code><eng>Proposed Indication/Use/Dosage (including maximum daily dose)</eng><fra>fr_Proposed Indication/Use/Dosage (including maximum daily dose)</fra></row>
<row><code>FORMULATION</code><eng>Formulation</eng><fra>fr_Formulation</fra></row>
<row><code>FORMULATIONS</code><eng>Formulations</eng><fra>fr_Formulations</fra></row>
<row><code>FORMULATION_NAME</code><eng>Formulation Name</eng><fra>fr_Formulation Name</fra></row>
<row><code>FORMULATION_DETAILS</code><eng>Formulation Record</eng><fra>fr_Formulation Record</fra></row>
<row><code>FORM_ID</code><eng>ID</eng><fra>fr_ID</fra></row>
<row><code>DOSAGE_FORM</code><eng>Dosage Form</eng><fra>fr_Dosage Form</fra></row>
<row><code>MEDICINAL_INGRED</code><eng>A. Medicinal (Active) Ingredients</eng><fra>fr_A. Medicinal (Active) Ingredients</fra></row>
<row><code>INGREDIENT</code><eng>Ingredient</eng><fra>fr_Ingredient</fra></row>
<row><code>IN_LIST</code><eng>In list</eng><fra>In list</fra></row>
<row><code>CAS_NUM</code><eng>Chemical Abstract Services</eng><fra>fr_Chemical Abstract Services</fra></row>
<row><code>ING_NAME</code><eng>Ingredient Name</eng><fra>fr_Ingredient Name</fra></row>
<row><code>STANDARD</code><eng>Standard</eng><fra>fr_Standard</fra></row>
<row><code>STRENGTH</code><eng>Strength</eng><fra>fr_Strength</fra></row>
<row><code>NOT_GREAT_THAN</code><eng>Not Great Than</eng><fra>fr_Not Great Than</fra></row>
<row><code>UNITS</code><eng>Units</eng><fra>fr_Units</fra></row>
<row><code>UNIT</code><eng>Unit</eng><fra>fr_Unit</fra></row>
<row><code>EQUALS</code><eng>Equals</eng><fra>fr_Equals</fra></row>
<row><code>NOT_LESS_THAN</code><eng>Not Less Than</eng><fra>fr_Not Less Than</fra></row>
<row><code>RANGE</code><eng>Range</eng><fra>fr_Range</fra></row>
<row><code>RANGE_LOWER_LIMIT</code><eng>Lower Limit</eng><fra>fr_Lower Limit</fra></row>
<row><code>RANGE_UPPER_LIMIT</code><eng>Upper Limit</eng><fra>fr_Upper Limit</fra></row>
<row><code>OTHER_UNIT_MEASURE</code><eng>Unit of Measure Other Details</eng><fra>fr_Unit of Measure Other Details</fra></row>
<row><code>PER_STRENGTH</code><eng>Per</eng><fra>fr_Per</fra></row>
<row><code>UNIT_PRESENTATION</code><eng>Unit of Presentation</eng><fra>fr_Unit of Presentation</fra></row>
<row><code>ISBASE</code><eng>Calculated as Base?</eng><fra>fr_Calculated as Base?</fra></row>
<row><code>IS_NANO_MATERIAL</code><eng>Is this a nanomaterial?</eng><fra>fr_Is this a nanomaterial?</fra></row>
<row><code>NANO_MATERIAL</code><eng>Nanomaterial</eng><fra>fr_Nanomaterial</fra></row>
<row><code>NANO_MATERIAL_OTHER</code><eng>Indicate the type of nanomaterial</eng><fra>fr_Indicate the type of nanomaterial</fra></row>
<row><code>ANIMAL_HUMAN_SOURCED</code><eng>Animal or Human Sourced?</eng><fra>fr_Animal or Human Sourced?</fra></row>
<row><code>IS_ANIMAL_HUMAN_MATERIAL</code><eng>Was Animal and/or Human Sourced Material used at any stage in the manufacturing of the drug?</eng><fra>fr_B.  Was Animal and/or Human Sourced Material used at any stage in the manufacturing of the drug?</fra></row>
<row><code>ANIMAL_HUMAN_HDING</code><eng>Animal and / or Human Sourced Materials used at any stage in the manufacture of the drug</eng><fra>fr_Animal and / or Human Sourced Materials used at any stage in the manufacture of the drug</fra></row>
<row><code>CONTAINER_TYPES</code><eng>Container Types, Package Size and Shelf Life</eng><fra>fr_C. Container Types</fra></row>
<row><code>MATERIAL_NAME</code><eng>Material Name</eng><fra>fr_Material Name</fra></row>
<row><code>PRESENT_IN_FINAL</code><eng>Present in final Container</eng><fra>fr_Present in final Container</fra></row>
<row><code>MATERIAL_DETAILS</code><eng>Animal and / or Human Sourced Materials Details</eng><fra>fr_Animal and / or Human Sourced Materials Details</fra></row>